name: sunday

on: 
  push:
  pull_request:

jobs:
  latest:
    runs-on: ubuntu-latest

    steps:
    - name: first step
      run: echo "Hello, Github Actions!"

    - name: second step
      run: echo "I am happy today!"

    - name: third step
      uses: actions/checkout@v7

    - name: fourth step
      run: |
        uname
        pwd
        ls -la   


  